/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class MediaFormatVideoVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MediaFormatVideoVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MediaFormatVideoVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_MediaFormatVideoVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MediaFormatVideoVector() {
    this(pjsua2JNI.new_MediaFormatVideoVector__SWIG_0(), true);
  }

  public MediaFormatVideoVector(long n) {
    this(pjsua2JNI.new_MediaFormatVideoVector__SWIG_1(n), true);
  }

  public long size() {
    return pjsua2JNI.MediaFormatVideoVector_size(swigCPtr, this);
  }

  public long capacity() {
    return pjsua2JNI.MediaFormatVideoVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    pjsua2JNI.MediaFormatVideoVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return pjsua2JNI.MediaFormatVideoVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    pjsua2JNI.MediaFormatVideoVector_clear(swigCPtr, this);
  }

  public void add(MediaFormatVideo x) {
    pjsua2JNI.MediaFormatVideoVector_add(swigCPtr, this, MediaFormatVideo.getCPtr(x), x);
  }

  public MediaFormatVideo get(int i) {
    return new MediaFormatVideo(pjsua2JNI.MediaFormatVideoVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, MediaFormatVideo val) {
    pjsua2JNI.MediaFormatVideoVector_set(swigCPtr, this, i, MediaFormatVideo.getCPtr(val), val);
  }

}
