/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class OnZrtpNegotiationFailedParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OnZrtpNegotiationFailedParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OnZrtpNegotiationFailedParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_OnZrtpNegotiationFailedParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCallId(int value) {
    pjsua2JNI.OnZrtpNegotiationFailedParam_callId_set(swigCPtr, this, value);
  }

  public int getCallId() {
    return pjsua2JNI.OnZrtpNegotiationFailedParam_callId_get(swigCPtr, this);
  }

  public void setSeverity(int value) {
    pjsua2JNI.OnZrtpNegotiationFailedParam_severity_set(swigCPtr, this, value);
  }

  public int getSeverity() {
    return pjsua2JNI.OnZrtpNegotiationFailedParam_severity_get(swigCPtr, this);
  }

  public void setSubCode(int value) {
    pjsua2JNI.OnZrtpNegotiationFailedParam_subCode_set(swigCPtr, this, value);
  }

  public int getSubCode() {
    return pjsua2JNI.OnZrtpNegotiationFailedParam_subCode_get(swigCPtr, this);
  }

  public OnZrtpNegotiationFailedParam() {
    this(pjsua2JNI.new_OnZrtpNegotiationFailedParam(), true);
  }

}
