/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class OnZrtpShowSASParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OnZrtpShowSASParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OnZrtpShowSASParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_OnZrtpShowSASParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCallId(int value) {
    pjsua2JNI.OnZrtpShowSASParam_callId_set(swigCPtr, this, value);
  }

  public int getCallId() {
    return pjsua2JNI.OnZrtpShowSASParam_callId_get(swigCPtr, this);
  }

  public void setSas(String value) {
    pjsua2JNI.OnZrtpShowSASParam_sas_set(swigCPtr, this, value);
  }

  public String getSas() {
    return pjsua2JNI.OnZrtpShowSASParam_sas_get(swigCPtr, this);
  }

  public void setVerified(int value) {
    pjsua2JNI.OnZrtpShowSASParam_verified_set(swigCPtr, this, value);
  }

  public int getVerified() {
    return pjsua2JNI.OnZrtpShowSASParam_verified_get(swigCPtr, this);
  }

  public OnZrtpShowSASParam() {
    this(pjsua2JNI.new_OnZrtpShowSASParam(), true);
  }

}
