/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjmedia_srtp_keying_method {
  public final static pjmedia_srtp_keying_method PJMEDIA_SRTP_KEYING_SDES = new pjmedia_srtp_keying_method("PJMEDIA_SRTP_KEYING_SDES");
  public final static pjmedia_srtp_keying_method PJMEDIA_SRTP_KEYING_DTLS_SRTP = new pjmedia_srtp_keying_method("PJMEDIA_SRTP_KEYING_DTLS_SRTP");
  public final static pjmedia_srtp_keying_method PJMEDIA_SRTP_KEYINGS_COUNT = new pjmedia_srtp_keying_method("PJMEDIA_SRTP_KEYINGS_COUNT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static pjmedia_srtp_keying_method swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + pjmedia_srtp_keying_method.class + " with value " + swigValue);
  }

  private pjmedia_srtp_keying_method(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private pjmedia_srtp_keying_method(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private pjmedia_srtp_keying_method(String swigName, pjmedia_srtp_keying_method swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static pjmedia_srtp_keying_method[] swigValues = { PJMEDIA_SRTP_KEYING_SDES, PJMEDIA_SRTP_KEYING_DTLS_SRTP, PJMEDIA_SRTP_KEYINGS_COUNT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

