/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjsua_dtmf_method {
  public final static pjsua_dtmf_method PJSUA_DTMF_METHOD_RFC2833 = new pjsua_dtmf_method("PJSUA_DTMF_METHOD_RFC2833");
  public final static pjsua_dtmf_method PJSUA_DTMF_METHOD_SIP_INFO = new pjsua_dtmf_method("PJSUA_DTMF_METHOD_SIP_INFO");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static pjsua_dtmf_method swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + pjsua_dtmf_method.class + " with value " + swigValue);
  }

  private pjsua_dtmf_method(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private pjsua_dtmf_method(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private pjsua_dtmf_method(String swigName, pjsua_dtmf_method swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static pjsua_dtmf_method[] swigValues = { PJSUA_DTMF_METHOD_RFC2833, PJSUA_DTMF_METHOD_SIP_INFO };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

