/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class RtcpFbCapVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RtcpFbCapVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RtcpFbCapVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_RtcpFbCapVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RtcpFbCapVector() {
    this(pjsua2JNI.new_RtcpFbCapVector__SWIG_0(), true);
  }

  public RtcpFbCapVector(long n) {
    this(pjsua2JNI.new_RtcpFbCapVector__SWIG_1(n), true);
  }

  public long size() {
    return pjsua2JNI.RtcpFbCapVector_size(swigCPtr, this);
  }

  public long capacity() {
    return pjsua2JNI.RtcpFbCapVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    pjsua2JNI.RtcpFbCapVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return pjsua2JNI.RtcpFbCapVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    pjsua2JNI.RtcpFbCapVector_clear(swigCPtr, this);
  }

  public void add(RtcpFbCap x) {
    pjsua2JNI.RtcpFbCapVector_add(swigCPtr, this, RtcpFbCap.getCPtr(x), x);
  }

  public RtcpFbCap get(int i) {
    return new RtcpFbCap(pjsua2JNI.RtcpFbCapVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, RtcpFbCap val) {
    pjsua2JNI.RtcpFbCapVector_set(swigCPtr, this, i, RtcpFbCap.getCPtr(val), val);
  }

}
