/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class SrtpCryptoVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SrtpCryptoVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SrtpCryptoVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_SrtpCryptoVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SrtpCryptoVector() {
    this(pjsua2JNI.new_SrtpCryptoVector__SWIG_0(), true);
  }

  public SrtpCryptoVector(long n) {
    this(pjsua2JNI.new_SrtpCryptoVector__SWIG_1(n), true);
  }

  public long size() {
    return pjsua2JNI.SrtpCryptoVector_size(swigCPtr, this);
  }

  public long capacity() {
    return pjsua2JNI.SrtpCryptoVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    pjsua2JNI.SrtpCryptoVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return pjsua2JNI.SrtpCryptoVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    pjsua2JNI.SrtpCryptoVector_clear(swigCPtr, this);
  }

  public void add(SrtpCrypto x) {
    pjsua2JNI.SrtpCryptoVector_add(swigCPtr, this, SrtpCrypto.getCPtr(x), x);
  }

  public SrtpCrypto get(int i) {
    return new SrtpCrypto(pjsua2JNI.SrtpCryptoVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, SrtpCrypto val) {
    pjsua2JNI.SrtpCryptoVector_set(swigCPtr, this, i, SrtpCrypto.getCPtr(val), val);
  }

}
