/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class ZrtpStateInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ZrtpStateInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZrtpStateInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_ZrtpStateInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    pjsua2JNI.ZrtpStateInfo_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return pjsua2JNI.ZrtpStateInfo_id_get(swigCPtr, this);
  }

  public void setSecure(boolean value) {
    pjsua2JNI.ZrtpStateInfo_secure_set(swigCPtr, this, value);
  }

  public boolean getSecure() {
    return pjsua2JNI.ZrtpStateInfo_secure_get(swigCPtr, this);
  }

  public void setSas(String value) {
    pjsua2JNI.ZrtpStateInfo_sas_set(swigCPtr, this, value);
  }

  public String getSas() {
    return pjsua2JNI.ZrtpStateInfo_sas_get(swigCPtr, this);
  }

  public void setCipher(String value) {
    pjsua2JNI.ZrtpStateInfo_cipher_set(swigCPtr, this, value);
  }

  public String getCipher() {
    return pjsua2JNI.ZrtpStateInfo_cipher_get(swigCPtr, this);
  }

  public void setSas_verified(boolean value) {
    pjsua2JNI.ZrtpStateInfo_sas_verified_set(swigCPtr, this, value);
  }

  public boolean getSas_verified() {
    return pjsua2JNI.ZrtpStateInfo_sas_verified_get(swigCPtr, this);
  }

  public ZrtpStateInfo() {
    this(pjsua2JNI.new_ZrtpStateInfo(), true);
  }

}
